---
- name: Run audit stage
  ansible.builtin.include_tasks: audit.yml
  when: cve_kernel_action_mode == 'audit'

- name: Run prepare stage
  ansible.builtin.include_tasks: prepare.yml
  when: cve_kernel_action_mode == 'prepare'

- name: Run reboot stage
  ansible.builtin.include_tasks: reboot.yml
  when: cve_kernel_action_mode == 'reboot'

- name: Run ssh-keysign mitigation stage
  ansible.builtin.include_tasks: mitigate_sshkeysign.yml
  when: cve_kernel_action_mode == 'mitigate_sshkeysign'
